off_FFC07B50:   dc.l unk_FFC085B0       ; DATA XREF: set_table_78↑o
                dc.l loc_FFCAFEF0
                dc.l loc_FFCAFF02
                dc.l loc_FFCAFFF0
                dc.l loc_FFCB0070
                dc.l loc_FFCB00E0
                dc.l loc_FFCB0130
                dc.l loc_FFCB0180
                dc.l loc_FFCB01D0
                dc.l loc_FFCB01E6
                dc.l loc_FFCB0290
                dc.l loc_FFCB02C0
                dc.l loc_FFCB0300
                dc.l loc_FFCB0340
                dc.l loc_FFCB0380
                dc.l loc_FFCB04C0
                dc.l loc_FFCB04E0
                dc.l sub_FFCB0590
                dc.l sub_FFCB05E0
                dc.l sub_FFCB0730
                dc.l sub_FFCB0770
                dc.l sub_FFCB07B0
                dc.l sub_FFCB0940
                dc.l sub_FFCB0B90
                dc.l sub_FFCB0DF0
                dc.l sub_FFCB0E90
                dc.l sub_FFCB0F00
                dc.l sub_FFCB1010
                dc.l sub_FFCB1150
                dc.l sub_FFCB1210
                dc.l sub_FFCB1340
                dc.l sub_FFCB14B0
                dc.l sub_FFCB1650
                dc.l sub_FFCB1730
                dc.l sub_FFCB1820
                dc.l sub_FFCB2410
                dc.l sub_FFCB24A0
                dc.l sub_FFCB24F0
                dc.l sub_FFCB2530
                dc.l sub_FFCB2580
                dc.l sub_FFCB25E0
                dc.l sub_FFCB2630
                dc.l sub_FFCB2800
                dc.l sub_FFCB28E0
                dc.l sub_FFCB29B0
                dc.l sub_FFCB2A90
                dc.l sub_FFCB2AE0
                dc.l sub_FFCB2BE0
                dc.l sub_FFCB2C20
                dc.l sub_FFCB2CC0
                dc.l sub_FFCB2EA0
                dc.l sub_FFCB2F80
                dc.l sub_FFCB3090
                dc.l sub_FFCB30B0
                dc.l sub_FFCB30E0
                dc.l sub_FFCB3130
                dc.l sub_FFCB31E0
                dc.l sub_FFCB3240
                dc.l sub_FFCB3270
                dc.l sub_FFCB3360
                dc.l sub_FFCB3390
                dc.l sub_FFCB34C0
                dc.l sub_FFCB3610
                dc.l sub_FFCB36D0
                dc.l sub_FFCB37F0
                dc.l sub_FFCB38A0
                dc.l sub_FFCB38F0
                dc.l sub_FFCB3970
                dc.l sub_FFCB39E0
                dc.l sub_FFCB1960
                dc.l sub_FFCB1C50
                dc.l sub_FFCB1D90
                dc.l sub_FFCB1F80
                dc.l sub_FFCB1FC0
                dc.l sub_FFCB21F0
                dc.l sub_FFCB22C0
                dc.l sub_FFCB2330
                dc.l sub_FFCB2390
                dc.l sub_FFC679D0
                dc.l 0
